facebook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'facebook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('main.urls'), name='main'),
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import patterns, url,include
from main import views
import social_auth

urlpatterns = patterns('',
    url(r'^$', views.main),
    url(r'contribute/', views.contribute),
    url(r'logout/', views.logout_view),
		url(r'user/(?P<id>\d+)/$', views.user),
    url(r'', include('social_auth.urls')),
)

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contribution(models.Model):
	title = models.CharField(max_length=50)
	body = models.TextField()
	user = models.ForeignKey(User)

main/views.py
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.shortcuts import render, render_to_response, redirect
from main.models import Contribution
from django.contrib.auth.models import User
from django.contrib.auth import logout

def main(request):
	contribution = Contribution.objects.all()
	print contribution
	context = {"contribution":contribution,"user":request.user}
	return render_to_response('main/index.html',context)
# Create your views here.

def user(request,id):
	print id
	print User.objects.get(id=id)
	contribution = Contribution.objects.filter(user_id=id)
	context = {"contribution":contribution,"myuser":request.user,"user":User.objects.get(id=id)}
	return render_to_response('main/user.html',context)

def logout_view(request):
	logout(request)
	return render_to_response("main/logout.html",RequestContext(request))

def contribute(request):
	if request.method == "POST": #requestがPOSTかGETか判別
		u = User.objects.get(id=request.user.id)
		c = Contribution()
		c.user = u
		c.title = request.POST["title"]
		c.body = request.POST["body"]
		c.save()
		return redirect("/")
	else:
		return render_to_response('main/contribute.html',RequestContext(request))

main/templates/main/contribute.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title>contribution</title>
</head>
<body>
<form action="/contribute/" method="POST">{% csrf_token %}
	<table>
	<tbody>
		<tr>
			<th>
				<label for="id_title">title:</label>
			</th>
			<td>
				<input id="id_title" type="text" name="title">
			</td>
		</tr>
		<tr>
			<th>
				<label for="id_body">body:</label>
			</th>
			<td>
				<textarea id="id_body" cols="20" rows="4" name="body"></textarea>
			</td>
		</tr>
	</tbody>
	</table>
	<input type="submit">
</form>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title>facebook</title>
</head>
<body>
	<a href="/user/{{ user.id }}">{{ user.username }}</a>でログイン中です<br>
	<a href="{% url 'socialauth_begin' 'facebook' %}">facebookでログイン</a>
	<a href="/logout">ログアウト</a>
	<br><a href="/contribute">投稿する</a>

	<table>
		<tr style="background-color:#00f;">
			<th>title</th>
			<td>body</td>
		</tr>
		{% for x in contribution %}
		<tr>
				<th>{{ x.title }}</th><td>{{ x.body }}</td>
		</tr>
		{% endfor %}
	</table>
</body>
</html>

main/templates/main/logout.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<a href="/">home</a>
</body>
</html>

main/templates/main/user.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title>facebook</title>
</head>
<body>
	<a href="/user/{{ myuser.id }}">{{ myuser.username }}</a>でログイン中です<br>
	<a href="{% url 'socialauth_begin' 'facebook' %}">facebookでログイン</a>
	<br><a href="/contribute">投稿する</a><br>
	{{ user.username }}の投稿一覧

	<table>
		<tr style="background-color:#00f;">
			<th>title</th>
			<td>body</td>
		</tr>
		{% for x in contribution %}
		<tr>
				<th>{{ x.title }}</th><td>{{ x.body }}</td>
		</tr>
		{% endfor %}
	</table>
</body>
</html>